
export const CST = {
    EMPTY: "Empty",
    SCENES: {
        MENU: "MENU",
        OPTIONS: "OPTIONS",
        PLAY: "PLAY",
        LOAD: "LOAD"
    },
    NUMBERS: {
        WIDTH: 1920,
        HEIGHT: 1080,
        ParusX: 580,
        ParusY: 580,
        DialogueButton: {
            x: 1675,
            y: 885
        },
        HeroSpawnArea: {
            X0: 810,
            Y0: 730,
            X1: 870,
            Y1: 820
        },
        MonsterSpawnArea: {
            X0: 1930,
            Y0: 730,
            X1: 2000,
            Y1: 820
        },
        SaveDataDelay: 1000,
        ManaRegenTime: 1000
    },
    IMAGES: {
        BackgroundEvening: 'backgroundEvening',
        BackgroundMenu: 'backgroundMenu',
        BackgroundOptions: 'backgroundOptions',
        Background: "background",
        SwitchON: "switchOn",
        SwitchONChoose: "switchOnChoose",
        SwitchOFF: "switchOff",
        SwitchOFFChoose: "switchOffChoose",
        EraseButton: "eraseButton",
        EraseButtonChoose: "eraseButtonChoose",
        Parus: "parus",
        CharacterWindow: "characterWindow",
        CharacterWindowChoose: "characterWindowChoose",
        PlayButton: 'playButton',
        PlayButtonChoose: 'playButtonChoose',
        BattleButton: "newWaveButton",
        BattleButtonChoose: "newWaveButtonChoose",
        OptionsButton: 'optionsButton',
        OptionsButtonChoose: 'optionsButtonChoose',
        BackButton: 'backButton',
        BackButtonChoose: 'backButtonChoose',
        StatusBar: "statusBar",
        ToolBarClose: "toolBarClose",
        ToolBarCloseChoose: "toolBarCloseChoose",
        ToolBarLeft: "toolBarLeft",
        ToolBarLeftChoose: "toolBarLeftChoose",
        ToolBarRight: "toolBarRight",
        ToolBarRightChoose: "toolBarRightChoose",
        ToolBarField: "toolBarField",
        HeroesBarClose: "heroesBarClose",
        HeroesBarCloseChoose: "heroesBarCloseChoose",
        HeroesBarField: "heroesBarField"
    },
    DIALOGUES: {
        DialogueButton: "dialogue_button",
        DialogueButtonHover: "dialogue_button_hover",
        Dialogue0: "dialogue_0",
        Dialogue1: "dialogue_1",
        Dialogue2: "dialogue_2",
        Dialogue3: "dialogue_3",
        Dialogue4: "dialogue_4",
        Dialogue5: "dialogue_5",
    },
    ICONS: {
        Parus: "icon_parus",
        BonusGold: "icon_coin",
        BonusExperience: "icon_experience",
        SpawnCooldown: "icon_cooldown",
        Damage: "icon_damage",
        HealPoints: "icon_hp",
        CriticalChance: "icon_critical_chance",
        CriticalDamage: "icon_critical_damage",
        ParusDefense: "icon_defense",
        Speed: "icon_speed",
        MPRecovery: "icon_mp",
        PhysicalDamage: "icon_physical_damage",
        MagicDamage: "icon_magic_damage",
        LightningDamage: "icon_lightning_damage",
        HeroCat: "iconHeroCat",
        HeroMage: "iconHeroMage",
        HeroArchaeologist: "iconHeroArchaeologist",
        HeroSceleton: "iconHeroSceleton",
        HeroCenturion: "iconHeroCenturion",
        HeroTesla: "iconHeroTesla",
        HeroWitch: "iconHeroWitch",
        HeroReaper: "iconHeroReaper",
        HeroNightmare: "iconHeroNightmare",
        HeroMinotaur: "iconHeroMinotaur",
        HeroStormhead: "iconHeroStormhead",
        HeroWizard: "iconHeroWizard",
        BuildingPodkova: "iconBuildingPodkova",
        BuildingMPObelisk: "iconBuildingMPObelisk",
        BuildingHPObelisk: "iconBuildingHPObelisk",
        BuildingCDObelisk: "iconBuildingCDObelisk",
        BuildingPlasmaGun: "iconBuildingPlasmaGun"
    },
    SPRITES32: {
        MonsterSlime: "monster_slime",
        MonsterTwig: "monster_twig",
        MonsterBrainer: "monster_brainer",
        MonsterGhoul: "monster_ghoul",
        MonsterDarkKnight: "monster_dark_knight",
        MonsterHedgehog: "monster_hedgehog",
        SummonGolem: "summon_golem",
        HeroCat: "hero_cat",
        HeroCenturion: "hero_centurion"
    },
    SPRITES40: {
        MonsterBot: "monster_bot",
    },
    SPRITES48: {
        MonsterHellhound: "monster_hellhound",
        HeroReaper: "hero_reaper",
        HeroSceleton: "hero_sceleton",
        HeroWitch: "hero_witch"
    },
    SPRITES64: {
        MonsterSlayer: "monster_slayer",
        MonsterIEM: "monster_iem",
        HeroMage: "hero_mage",
        HeroTesla: "hero_tesla",
        HeroArchaeologist: "hero_archaeologist",
        Thunderstrike: "thunderstrike"
    },
    SPRITES80: {
        MonsterNanny: "monster_nanny",
        HeroNightmare: "hero_nightmare",
        HeroWizard: "hero_wisard"
    },
    SPRITES90: {
        MonsterWorm: "monster_worm",
    },
    SPRITES96: {
        HeroMinotaur: "hero_minotaur",
        MonsterSprout: "monster_sprout"
    },
    SPRITES100: {
        MonsterReaper: "monster_reaper",
    },
    SPRITES120: {
        MonsterGuardian: "monster_guardian"
    },
    SPRITES128: {
        HeroStormhead: "hero_stormhead",
        MonsterNecromancer: "monster_necromancer"
    },
    SPRITES140: {
        MonsterBringer: "monster_bringer"
    },
    SPRITES150: {
        MonsterFireWizard: "monster_fire_wizard"
    },
    SPRITES196: {
        MonsterMiner: "monster_miner"
    },
    SPRITES200: {
        BossCultist: "boss_cultist",
        BossMiranda: "boss_miranda",
    },
    SPRITES240: {
        BossDemon: "boss_demon",
    },
    SPRITES250: {
        MonsterSoulWizard: "monster_soul_wizard",
    },
    SPRITES360: {
        BuildingPodkova: "building_podkova",
    },
    SPRITE_MP_OBELISK: {
        BuildingMPObelisk: "building_mp_obelisk",
    },
    SPRITE_HP_OBELISK: {
        BuildingHPObelisk: "building_hp_obelisk",
    },
    SPRITE_CD_OBELISK: {
        BuildingCDObelisk: "building_cd_obelisk",
    },
    SPRITE_PLASMA_GUN: {
        BuildingPlasmaGun: "building_plasma_gun",
    },
    SPRITE_TOASTER: {
        MonsterToaster: "monster_toaster",
    },
    SPRITESDRAGON: {
        BossBlackDragon: "boss_black_dragon"
    },
    SPRITECTHULHU: {
        BossCthulhu: "boss_cthulhu"
    },
    MUSIC: {
        Psychosocial: "8-Bit_Misfits_Psychosocial",
        Centuries: "8-Bit_Misfits_Centuries",
        GetLucky: "8-Bit_Misfits_Get_Lucky",
        ImmigrantSong: "8-Bit_Misfits_Immigrant_Song",
        Tattoo: "Rammstein_Tattoo",
        NeroForte: "8-Bit_Misfits_Nero_Forte",
        TheDevilInI: "8-Bit_Misfits_The_Devil_in_I"
    },
    SOUNDS: {
        BossCthulhuDeath: "BossCthulhuDeath",
        BossCthulhuHit: "BossCthulhuHit",
        BossCthulhuMove: "BossCthulhuMove",
        BossCultistDeath: "BossCultistDeath",
        BossCultistHit: "BossCultistHit",
        BossCultistMove: "BossCultistMove",
        BossDemonDeath: "BossDemonDeath",
        BossDemonHit: "BossDemonHit",
        BossDemonMove: "BossDemonMove",
        BossDragonDeath: "BossDragonDeath",
        BossDragonHit: "BossDragonHit",
        BossDragonMove: "BossDragonMove",
        BossMirandaDeath: "BossMirandaDeath",
        BossMirandaHit: "BossMirandaHit",
        BossMirandaMove : "BossMirandaMove",
        HeroArchaeologistDeath: "HeroArchaeologistDeath",
        HeroArchaeologistHit: "HeroArchaeologistHit",
        HeroCatDeath: "HeroCatDeath",
        HeroCatHit: "HeroCatHit",
        HeroCenturionDeath: "HeroCenturionDeath",
        HeroCenturionHit: "HeroCenturionHit",
        HeroMageDeath: "HeroMageDeath",
        HeroMageHit: "HeroMageHit",
        HeroMinotaurDeath: "HeroMinotaurDeath",
        HeroMinotaurHit: "HeroMinotaurHit",
        HeroNightmareDeath: "HeroNightmareDeath",
        HeroNightmareHit: "HeroNightmareHit",
        HeroReaperDeath: "HeroReaperDeath",
        HeroReaperHit: "HeroReaperHit",
        HeroSceletonDeath: "HeroSceletonDeath",
        HeroSceletonHit: "HeroSceletonHit",
        HeroStormheadDeath: "HeroStormheadDeath",
        HeroStormheadHit: "HeroStormheadHit",
        HeroTeslaHit: "HeroTeslaHit",
        HeroTeslaDeath: "HeroTeslaDeath",
        HeroWitchDeath: "HeroWitchDeath",
        HeroWitchHit: "HeroWitchHit",
        HeroWizardDeath: "HeroWizardDeath",
        HeroWizardHit: "HeroWizardHit",
        MonsterBotHit: "MonsterBotHit",
        MonsterBotDeath: "MonsterBotDeath",
        MonsterBrainerHit: "MonsterBrainerHit",
        MonsterBrainerDeath: "MonsterBrainerDeath",
        MonsterBringerDeath: "MonsterBringerDeath",
        MonsterBringerHit: "MonsterBringerHit",
        MonsterDarkKnightDeath: "MonsterDarkKnightDeath",
        MonsterDarkKnightHit: "MonsterDarkKnightHit",
        MonsterFireWizardDeath: "MonsterFireWizardDeath",
        MonsterFireWizardHit: "MonsterFireWizardHit",
        MonsterGhoulDeath: "MonsterGhoulDeath",
        MonsterGhoulHit: "MonsterGhoulHit",
        MonsterGuardianDeath: "MonsterGuardianDeath",
        MonsterGuardianHit: "MonsterGuardianHit",
        MonsterHedgehogDeath: "MonsterHedgehogDeath",
        MonsterHedgehogHit: "MonsterHedgehogHit",
        MonsterHellhoundDeath: "MonsterHellhoundDeath",
        MonsterHellHoundHit: "MonsterHellHoundHit",
        MonsterIEMDeath: "MonsterIEMDeath",
        MonsterIEMHit: "MonsterIEMHit",
        MonsterMinerDeath: "MonsterMinerDeath",
        MonsterMinerHit: "MonsterMinerHit",
        MonsterNannyDeath: "MonsterNannyDeath",
        MonsterNannyHit: "MonsterNannyHit",
        MonsterNecromancerDeath: "MonsterNecromancerDeath",
        MonsterNecromancerHit: "MonsterNecromancerHit",
        MonsterReaperDeath: "MonsterReaperDeath",
        MonsterReaperHit: "MonsterReaperHit",
        MonsterSlayerHit: "MonsterSlayerHit",
        MonsterSlimeDeath: "MonsterSlimeDeath",
        MonsterSlimeHit: "MonsterSlimeHit",
        MonsterSlimeMove: "MonsterSlimeMove",
        MonsterSoulWizardDeath: "MonsterSoulWizardDeath",
        MonsterSoulWizardHit: "MonsterSoulWizardHit",
        MonsterSproutDeath: "MonsterSproutDeath",
        MonsterSproutHit: "MonsterSproutHit",
        MonsterSproutMove: "MonsterSproutMove",
        MonsterToasterDeath: "MonsterToasterDeath",
        MonsterToasterHit: "MonsterToasterHit",
        MonsterTwigDeath: "MonsterTwigDeath",
        MonsterTwigHit: "MonsterTwigHit",
        MonsterTwigMove: "MonsterTwigMove",
        MonsterWormDeath: "MonsterWormDeath",
        MonsterWormHit: "MonsterWormHit",
        MonstrSlayerDeath: "MonstrSlayerDeath"
    },
    EFFECTS: {
        Thunderstrike: "thunderstrike"
    },
    MONSTERLIST: ["MonsterSlime", "MonsterTwig", "MonsterBrainer", "MonsterHellhound", "MonsterGhoul", "MonsterDarkKnight", "MonsterBot", "MonsterToaster", "MonsterHedgehog", "MonsterSlayer", "MonsterIEM", "MonsterNecromancer", "MonsterWorm", "MonsterReaper", "MonsterBringer", "MonsterSprout", "MonsterNanny", "MonsterSoulWizard", "MonsterFireWizard", "MonsterGuardian", "MonsterMiner"],
    BOSSLIST: ["BossCultist", "BossBlackDragon", "BossCthulhu", "BossDemon", "BossMiranda"],
    HEROLIST: ["HeroCat", "HeroReaper", "HeroArchaeologist", "HeroCenturion", "HeroMage", "HeroTesla", "HeroMinotaur", "HeroNightmare", "HeroSceleton", "HeroWitch", "HeroStormhead", "HeroWizard"],
    SHOPLIST: {
        Parus: {
            Name: "Парус",
            Description: "Увеличение HP и \nMP Паруса",
            BeginCost: 500
        },
        HeroCat: {
            Name: "Кот-рыцарь",
            Description: "Увеличение HP и \nурона Кота",
            BeginCost: 500
        },
        HeroReaper: {
            Name: "Жнец",
            Description: "Увеличение HP и \nурона Жнеца",
            BeginCost: 1000
        },
        HeroArchaeologist: {
            Name: "Археолог",
            Description: "Увеличение HP и \nурона Археолога",
            BeginCost: 1000
        },
        HeroCenturion: {
            Name: "Центурион Рори",
            Description: "Увеличение HP и \nурона Рори",
            BeginCost: 2000
        },
        HeroMage: {
            Name: "Тёмный Маг",
            Description: "Увеличение HP и \nурона Мага",
            BeginCost: 2000
        },
        HeroTesla: {
            Name: "Тесла",
            Description: "Увеличение HP и \nурона Тесла",
            BeginCost: 2500
        },
        HeroSceleton: {
            Name: "Big Bone",
            Description: "Увеличение HP и \nурона Big Bon`а",
            BeginCost: 2500
        },
        HeroWitch: {
            Name: "Ведьмочка",
            Description: "Увеличение HP и \nурона Ведьмы",
            BeginCost: 3000
        },
        HeroNightmare: {
            Name: "Кошмар",
            Description: "Увеличение HP и \nурона Кошмара",
            BeginCost: 5000
        },
        HeroMinotaur: {
            Name: "Минотавр",
            Description: "Увеличение HP и \nурона Минотавра",
            BeginCost: 5000
        },
        HeroStormhead: {
            Name: "Ш.Т.О.Р.М",
            Description: "Увеличение HP и \nурона Ш.Т.О.Р.М",
            BeginCost: 5000
        },
        HeroWizard: {
            Name: "Чародей",
            Description: "Увеличение HP и \nурона Чародея",
            BeginCost: 5000
        },
        BuildingPodkova: {
            Name: "Подкова",
            Description: "Увеличение кол-ва \nвыпадающих монет \n(+1%/LVL)",
            BeginCost: 20000
        },
        BuildingMPObelisk: {
            Name: "Обелиск Магии",
            Description: "Мгновенно \nвосстанавливает 50% MP",
            BeginCost: 30000
        },
        BuildingHPObelisk: {
            Name: "Обелиск Жизни",
            Description: "Мгновенно \nвосстанавливает 50% HP",
            BeginCost: 30000
        },
        BuildingCDObelisk: {
            Name: "Обелиск Времени",
            Description: "Мгновенно \nобнуляет перезарядку \nгероев",
            BeginCost: 30000
        },
        BuildingPlasmaGun: {
            Name: "BFG-9000",
            Description: "Уничтожает всех \nпротивников на поле",
            BeginCost: 50000
        }
    },
    SKILLSLIST: {
        BonusGold: {
            Name: "Бонусные монеты",
            Description: "Увеличение выпадаемых \nмонет",
            Levels: [
                "+0%",
                "+2.5%",
                "+5%",
                "+7.5%",
                "+10%",
                "+12.5%",
                "+15%",
                "+17.5%",
                "+20%",
                "+22.5%",
                "+25%",
                "+27.5%",
                "+30%",
                "+32.5%",
                "+35%",
                "+37.5%",
                "+40%",
                "+42.5%",
                "+45%",
                "+47.5%",
                "+50%"
            ]
        },
        BonusExperience: {
            Name: "Бонусный опыт",
            Description: "Увеличение выпадемого \nопыта",
            Levels: [
                "+0%",
                "+5%",
                "+10%",
                "+15%",
                "+20%",
                "+25%",
                "+30%",
                "+35%",
                "+40%",
                "+45%",
                "+50%",
                "+55%",
                "+60%",
                "+65%",
                "+70%",
                "+75%",
                "+80%",
                "+85%",
                "+90%",
                "+95%",
                "+100%"
            ]
        },
        SpawnCooldown: {
            Name: "Перезарядка",
            Description: "Уменьшение времени \nмежду вызовами героев",
            Levels: [
                "-0%",
                "-2.5%",
                "-5%",
                "-7.5%",
                "-10%",
                "-12.5%",
                "-15%",
                "-17.5%",
                "-20%",
                "-22.5%",
                "-25%",
                "-27.5%",
                "-30%",
                "-32.5%",
                "-35%",
                "-37.5%",
                "-40%",
                "-42.5%",
                "-45%",
                "-47.5%",
                "-50%"
            ]
        },
        Damage: {
            Name: "Урон",
            Description: "Увеличение урона",
            Levels: [
                "+0%",
                "+1.25%",
                "+2.5%",
                "+3.75%",
                "+5%",
                "+6.25%",
                "+7.5%",
                "+8.75%",
                "+10%",
                "+11.25%",
                "+12.5%",
                "+13.75%",
                "+15%",
                "+16.25%",
                "+17.5%",
                "+18.75%",
                "+20%",
                "+21.25%",
                "+22.5%",
                "+23.75%",
                "+25%"
            ]
        },
        HealPoints: {
            Name: "Здоровье",
            Description: "Увеличение здоровья",
            Levels: [
                "+0%",
                "+1.25%",
                "+2.5%",
                "+3.75%",
                "+5%",
                "+6.25%",
                "+7.5%",
                "+8.75%",
                "+10%",
                "+11.25%",
                "+12.5%",
                "+13.75%",
                "+15%",
                "+16.25%",
                "+17.5%",
                "+18.75%",
                "+20%",
                "+21.25%",
                "+22.5%",
                "+23.75%",
                "+25%"
            ]
        },
        CriticalChance: {
            Name: "Критический шанс",
            Description: "Увеличение шанса \nкритического урона",
            Levels: [
                "0%",
                "+1%",
                "+2%",
                "+3%",
                "+4%",
                "+5%",
                "+6%",
                "+7%",
                "+8%",
                "+9%",
                "+10%",
                "+11%",
                "+12%",
                "+13%",
                "+14%",
                "+15%",
                "+16%",
                "+17%",
                "+18%",
                "+19%",
                "+20%"
            ]
        },
        CriticalDamage: {
            Name: "Критический урон",
            Description: "Увеличение критического \nурона",
            Levels: [
                "0%",
                "+1%",
                "+2%",
                "+3%",
                "+4%",
                "+5%",
                "+6%",
                "+7%",
                "+8%",
                "+9%",
                "+10%",
                "+11%",
                "+12%",
                "+13%",
                "+14%",
                "+15%",
                "+16%",
                "+17%",
                "+18%",
                "+19%",
                "+20%"
            ]
        },
        ParusDefense: {
            Name: "Защищенность",
            Description: "Увеличение защищенности \nПаруса",
            Levels: [
                "+0%",
                "+2.5%",
                "+5%",
                "+7.5%",
                "+10%",
                "+12.5%",
                "+15%",
                "+17.5%",
                "+20%",
                "+22.5%",
                "+25%",
                "+27.5%",
                "+30%",
                "+32.5%",
                "+35%",
                "+37.5%",
                "+40%",
                "+42.5%",
                "+45%",
                "+47.5%",
                "+50%"
            ]
        },
        Speed: {
            Name: "Скорость",
            Description: "Увеличение скорости \nпередвижения героев",
            Levels: [
                "+0%",
                "+5%",
                "+10%",
                "+15%",
                "+20%",
                "+25%",
                "+30%",
                "+35%",
                "+40%",
                "+45%",
                "+50%",
                "+55%",
                "+60%",
                "+65%",
                "+70%",
                "+75%",
                "+80%",
                "+85%",
                "+90%",
                "+95%",
                "+100%"
            ]
        },
        MPRecovery: {
            Name: "Регенерация маны",
            Description: "Увеличение скорости \nвосстановления маны",
            Levels: [
                "+0%",
                "+5%",
                "+10%",
                "+15%",
                "+20%",
                "+25%",
                "+30%",
                "+35%",
                "+40%",
                "+45%",
                "+50%",
                "+55%",
                "+60%",
                "+65%",
                "+70%",
                "+75%",
                "+80%",
                "+85%",
                "+90%",
                "+95%",
                "+100%"
            ]
        },
        PhysicalDamage: {
            Name: "Физический урон",
            Description: "Увеличение физического \nурона",
            Levels: [
                "+0%",
                "+2.5%",
                "+5%",
                "+7.5%",
                "+10%",
                "+12.5%",
                "+15%",
                "+17.5%",
                "+20%",
                "+22.5%",
                "+25%",
                "+27.5%",
                "+30%",
                "+32.5%",
                "+35%",
                "+37.5%",
                "+40%",
                "+42.5%",
                "+45%",
                "+47.5%",
                "+50%"
            ]
        },
        MagicDamage: {
            Name: "Магический урон",
            Description: "Увеличение магического \nурона",
            Levels: [
                "+0%",
                "+2.5%",
                "+5%",
                "+7.5%",
                "+10%",
                "+12.5%",
                "+15%",
                "+17.5%",
                "+20%",
                "+22.5%",
                "+25%",
                "+27.5%",
                "+30%",
                "+32.5%",
                "+35%",
                "+37.5%",
                "+40%",
                "+42.5%",
                "+45%",
                "+47.5%",
                "+50%"
            ]
        },
        LightningDamage: {
            Name: "Электрический урон",
            Description: "Увеличение электрического \nурона",
            Levels: [
                "+0%",
                "+2.5%",
                "+5%",
                "+7.5%",
                "+10%",
                "+12.5%",
                "+15%",
                "+17.5%",
                "+20%",
                "+22.5%",
                "+25%",
                "+27.5%",
                "+30%",
                "+32.5%",
                "+35%",
                "+37.5%",
                "+40%",
                "+42.5%",
                "+45%",
                "+47.5%",
                "+50%"
            ]
        }
    },
    ANIMATIONS: {
        SummonGolem: {
            Idle: 'summon_golem_idle',
            Walk: 'summon_golem_walk',
            Hit: 'summon_golem_hit',
            Death: 'summon_golem_death'
        },
        MonsterSlime: {
            Idle: 'monster_slime_idle',
            Walk: 'monster_slime_walk',
            Hit: 'monster_slime_hit',
            Death: 'monster_slime_death'
        },
        MonsterTwig: {
            Idle: 'monster_twig_idle',
            Walk: 'monster_twig_walk',
            Hit: 'monster_twig_hit',
            Death: 'monster_twig_death'
        },
        MonsterBrainer: {
            Idle: 'monster_brainer_idle',
            Walk: 'monster_brainer_walk',
            Hit: 'monster_brainer_hit',
            Death: 'monster_brainer_death'
        },
        MonsterHellhound: {
            Idle: 'monster_hellhound_idle',
            Walk: 'monster_hellhound_walk',
            Hit: 'monster_hellhound_hit',
            Death: 'monster_hellhound_death'
        },
        MonsterGhoul: {
            Idle: 'monster_ghoul_idle',
            Walk: 'monster_ghoul_walk',
            Hit: 'monster_ghoul_hit',
            Death: 'monster_ghoul_death'
        },
        MonsterBot: {
            Idle: 'monster_bot_idle',
            Walk: 'monster_bot_walk',
            Hit: 'monster_bot_hit',
            Death: 'monster_bot_death'
        },
        MonsterDarkKnight: {
            Idle: 'monster_dark_knight_idle',
            Walk: 'monster_dark_knight_walk',
            Hit: 'monster_dark_knight_hit',
            Death: 'monster_dark_knight_death'
        },
        MonsterHedgehog: {
            Idle: 'monster_hedgehog_idle',
            Walk: 'monster_hedgehog_walk',
            Hit: 'monster_hedgehog_hit',
            Death: 'monster_hedgehog_death'
        },
        MonsterSlayer: {
            Idle: 'monster_slayer_idle',
            Walk: 'monster_slayer_walk',
            Hit: 'monster_slayer_hit',
            Death: 'monster_slayer_death'
        },
        MonsterToaster: {
            Idle: 'monster_toaster_idle',
            Walk: 'monster_toaster_walk',
            Hit: 'monster_toaster_hit',
            Death: 'monster_toaster_death'
        },
        MonsterWorm: {
            Idle: 'monster_worm_idle',
            Walk: 'monster_worm_walk',
            Hit: 'monster_worm_hit',
            Death: 'monster_worm_death'
        },
        MonsterBringer: {
            Idle: 'monster_bringer_idle',
            Walk: 'monster_bringer_walk',
            Hit: 'monster_bringer_hit',
            Death: 'monster_bringer_death'
        },
        MonsterIEM: {
            Idle: 'monster_iem_idle',
            Walk: 'monster_iem_walk',
            Hit: 'monster_iem_hit',
            Death: 'monster_iem_death'
        },
        MonsterSprout: {
            Idle: 'monster_sprout_idle',
            Walk: 'monster_sprout_walk',
            Hit: 'monster_sprout_hit',
            Death: 'monster_sprout_death'
        },
        MonsterNecromancer: {
            Idle: 'monster_necromancer_idle',
            Walk: 'monster_necromancer_walk',
            Hit: 'monster_necromancer_hit',
            Death: 'monster_necromancer_death'
        },
        MonsterReaper: {
            Idle: 'monster_reaper_idle',
            Walk: 'monster_reaper_walk',
            Hit: 'monster_reaper_hit',
            Death: 'monster_reaper_death'
        },
        MonsterSoulWizard: {
            Idle: 'monster_soul_wizard_idle',
            Walk: 'monster_soul_wizard_walk',
            Hit: 'monster_soul_wizard_hit',
            Death: 'monster_soul_wizard_death'
        },
        MonsterFireWizard: {
            Idle: 'monster_fire_wizard_idle',
            Walk: 'monster_fire_wizard_walk',
            Hit: 'monster_fire_wizard_hit',
            Death: 'monster_fire_wizard_death'
        },
        MonsterGuardian: {
            Idle: 'monster_guardian_idle',
            Walk: 'monster_guardian_walk',
            Hit: 'monster_guardian_hit',
            Death: 'monster_guardian_death'
        },
        MonsterMiner: {
            Idle: 'monster_miner_idle',
            Walk: 'monster_miner_walk',
            Hit: 'monster_miner_hit',
            Death: 'monster_miner_death'
        },
        MonsterNanny: {
            Idle: 'monster_nanny_idle',
            Walk: 'monster_nanny_walk',
            Hit: 'monster_nanny_hit',
            Death: 'monster_nanny_death'
        },
        BossCultist: {
            Idle: 'boss_cultist_idle',
            Walk: 'boss_cultist_walk',
            Hit: 'boss_cultist_hit',
            Death: 'boss_cultist_death'
        },
        BossBlackDragon: {
            Idle: 'boss_black_dragon_idle',
            Walk: 'boss_black_dragon_walk',
            Hit: 'boss_black_dragon_hit',
            Death: 'boss_black_dragon_death'
        },
        BossCthulhu: {
            Idle: 'boss_cthulhu_idle',
            Walk: 'boss_cthulhu_walk',
            Brainstorm: 'boss_cthulhu_brainstorm',
            Tentacle: 'boss_cthulhu_tentacle',
            Death: 'boss_cthulhu_death'
        },
        BossDemon: {
            Idle: 'boss_demon_idle',
            Walk: 'boss_demon_walk',
            Hit: 'boss_demon_hit',
            Death: 'boss_demon_death'
        },
        BossMiranda: {
            Idle: 'boss_miranda_idle',
            Walk: 'boss_miranda_walk',
            Hit: 'boss_miranda_hit',
            Death: 'boss_miranda_death'
        },
        HeroCat: {
            Idle: 'hero_cat_idle',
            IdleWindow: 'hero_cat_idle_window',
            Walk: 'hero_cat_walk',
            Hit: 'hero_cat_hit',
            Death: 'hero_cat_death'
        },
        HeroMage: {
            Idle: 'hero_mage_idle',
            IdleWindow: 'hero_mage_idle_window',
            Walk: 'hero_mage_walk',
            Hit: 'hero_mage_hit',
            Death: 'hero_mage_death'
        },
        HeroArchaeologist: {
            Idle: 'hero_archaeologist_idle',
            IdleWindow: 'hero_archaeologist_idle_window',
            Walk: 'hero_archaeologist_walk',
            Hit: 'hero_archaeologist_hit',
            Death: 'hero_archaeologist_death'
        },
        HeroSceleton: {
            Idle: 'hero_sceleton_idle',
            IdleWindow: 'hero_sceleton_idle_window',
            Walk: 'hero_sceleton_walk',
            Hit: 'hero_sceleton_hit',
            Death: 'hero_sceleton_death'
        },
        HeroTesla: {
            Idle: 'hero_tesla_idle',
            IdleWindow: 'hero_tesla_idle_window',
            Walk: 'hero_tesla_walk',
            Hit: 'hero_tesla_hit',
            Death: 'hero_tesla_death'
        },
        HeroWitch: {
            Idle: 'hero_witch_idle',
            IdleWindow: 'hero_witch_idle_window',
            Walk: 'hero_witch_walk',
            Hit: 'hero_witch_hit',
            Death: 'hero_witch_death'
        },
        HeroCenturion: {
            Idle: 'hero_centurion_idle',
            IdleWindow: 'hero_centurion_idle_window',
            Walk: 'hero_centurion_walk',
            Hit: 'hero_centurion_hit',
            Death: 'hero_centurion_death'
        },
        HeroReaper: {
            Idle: 'hero_reaper_idle',
            IdleWindow: 'hero_reaper_idle_window',
            Walk: 'hero_reaper_walk',
            Hit: 'hero_reaper_hit',
            Death: 'hero_reaper_death'
        },
        HeroNightmare: {
            Idle: 'hero_nightmare_idle',
            IdleWindow: 'hero_nightmare_idle_window',
            Walk: 'hero_nightmare_walk',
            Hit: 'hero_nightmare_hit',
            Death: 'hero_nightmare_death'
        },
        HeroMinotaur: {
            Idle: 'hero_minotaur_idle',
            IdleWindow: 'hero_minotaur_idle_window',
            Walk: 'hero_minotaur_walk',
            Hit: 'hero_minotaur_hit',
            Death: 'hero_minotaur_death'
        },
        HeroStormhead: {
            Idle: 'hero_stormhead_idle',
            IdleWindow: 'hero_stormhead_idle_window',
            Walk: 'hero_stormhead_walk',
            Hit: 'hero_stormhead_hit',
            Death: 'hero_stormhead_death'
        },
        HeroWizard: {
            Idle: 'hero_wizard_idle',
            IdleWindow: 'hero_wizard_idle_window',
            Walk: 'hero_wizard_walk',
            Hit: 'hero_wizard_hit',
            Death: 'hero_wizard_death'
        },
        BuildingPodkova: {
            Idle: 'building_podkova_idle',
            Use: 'building_podkova_use'
        },
        BuildingMPObelisk: {
            Idle: 'building_mp_obelisk_idle',
            Use: 'building_mp_obelisk_use',
        },
        BuildingHPObelisk: {
            Idle: 'building_hp_obelisk_idle',
            Use: 'building_hp_obelisk_use',
        },
        BuildingCDObelisk: {
            Idle: 'building_cd_obelisk_idle',
            Use: 'building_cd_obelisk_use',
        },
        BuildingPlasmaGun: {
            Idle: 'building_plasma_gun_idle',
            Use: 'building_plasma_gun_use',
        }
    },
    CHARACTERS: {
        SummonGolem: {
            Name: "SummonGolem",
            HealPoints: 300,
            PhysicalDamage: 10,
            LightningDamage: 10,
            MagicDamage: 10,
            AttackCooldown: 1000,
            Speed: 60,
            PhysicalProtection: 10,
            LightningProtection: 10,
            MagicProtection: 10,
            Cost: 15,
            Experience: 5,
            Range: 50,
            EnemyControl: 4,
            ParusPriority: false
        },
        MonsterSlime: {
            Name: "MonsterSlime",
            HealPoints: 250,
            PhysicalDamage: 10,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 90,
            PhysicalProtection: 0,
            LightningProtection: 0,
            MagicProtection: 0,
            Cost: 25,
            Experience: 5,
            Range: 30,
            EnemyControl: 2,
            ParusPriority: false
        },
        MonsterTwig: {
            Name: "MonsterTwig",
            HealPoints: 400,
            PhysicalDamage: 15,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 150,
            PhysicalProtection: 10,
            LightningProtection: 0,
            MagicProtection: 0,
            Cost: 50,
            Experience: 20,
            Range: 60,
            EnemyControl: 3,
            ParusPriority: false
        },
        MonsterBrainer: {
            Name: "MonsterBrainer",
            HealPoints: 700,
            PhysicalDamage: 30,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 90,
            PhysicalProtection: 0,
            LightningProtection: 10,
            MagicProtection: 0,
            Cost: 100,
            Experience: 30,
            Range: 60,
            EnemyControl: 3,
            ParusPriority: false
        },
        MonsterHellhound: {
            Name: "MonsterHellhound",
            HealPoints: 800,
            PhysicalDamage: 50,
            LightningDamage: 0,
            MagicDamage: 10,
            AttackCooldown: 1500,
            Speed: 190,
            PhysicalProtection: 0,
            LightningProtection: 0,
            MagicProtection: 10,
            Cost: 125,
            Experience: 50,
            Range: 60,
            EnemyControl: 6,
            ParusPriority: true
        },
        MonsterGhoul: {
            Name: "MonsterGhoul",
            HealPoints: 800,
            PhysicalDamage: 70,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 100,
            PhysicalProtection: 10,
            LightningProtection: 0,
            MagicProtection: 10,
            Cost: 150,
            Experience: 100,
            Range: 60,
            EnemyControl: 3,
            ParusPriority: false
        },
        MonsterDarkKnight: {
            Name: "MonsterDarkKnight",
            HealPoints: 1000,
            PhysicalDamage: 100,
            LightningDamage: 0,
            MagicDamage: 5,
            AttackCooldown: 1000,
            Speed: 70,
            PhysicalProtection: 50,
            LightningProtection: 10,
            MagicProtection: 20,
            Cost: 200,
            Experience: 120,
            Range: 50,
            EnemyControl:4,
            ParusPriority:false
        },
        MonsterBot: {
            Name: "MonsterBot",
            HealPoints: 1200,
            PhysicalDamage: 0,
            LightningDamage: 100,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 80,
            PhysicalProtection: 20,
            LightningProtection: 0,
            MagicProtection: 50,
            Cost: 250,
            Experience: 140,
            Range: 100,
            EnemyControl: 5,
            ParusPriority: false
        },
        MonsterToaster: {
            Name: "MonsterToaster",
            HealPoints: 1300,
            PhysicalDamage: 50,
            LightningDamage: 50,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 40,
            PhysicalProtection: 20,
            LightningProtection: 0,
            MagicProtection: 50,
            Cost: 275,
            Experience: 160,
            Range: 50,
            EnemyControl: 4,
            ParusPriority: false
        },
        MonsterHedgehog: {
            Name: "MonsterHedgehog",
            HealPoints: 2000,
            PhysicalDamage: 50,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 75,
            PhysicalProtection: 40,
            LightningProtection: 0,
            MagicProtection: 0,
            Cost: 300,
            Experience: 180,
            Range: 20,
            EnemyControl: 5,
            ParusPriority: false
        },
        MonsterSlayer: {
            Name: "MonsterSlayer",
            HealPoints: 1500,
            PhysicalDamage: 150,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 50,
            PhysicalProtection: 10,
            LightningProtection: 0,
            MagicProtection: 10,
            Cost: 325,
            Experience: 200,
            Range: 60,
            EnemyControl: 5,
            ParusPriority: false
        },
        MonsterIEM: {
            Name: "MonsterIEM",
            HealPoints: 1750,
            PhysicalDamage: 0,
            LightningDamage: 0,
            MagicDamage: 100,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 70,
            LightningProtection: 0,
            MagicProtection: 0,
            Cost: 350,
            Experience: 220,
            Range: 60,
            EnemyControl:4,
            ParusPriority:true
        },
        MonsterNecromancer: {
            Name: "MonsterNecromancer",
            HealPoints: 2000,
            PhysicalDamage: 0,
            LightningDamage: 0,
            MagicDamage: 150,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 20,
            LightningProtection: 20,
            MagicProtection: 20,
            Cost: 375,
            Experience: 250,
            Range: 60,
            EnemyControl:4,
            ParusPriority:false
        },
        MonsterWorm: {
            Name: "MonsterWorm",
            HealPoints: 1500,
            PhysicalDamage: 50,
            LightningDamage: 0,
            MagicDamage: 150,
            AttackCooldown: 1000,
            Speed: 40,
            PhysicalProtection: 0,
            LightningProtection: 10,
            MagicProtection: 0,
            Cost: 400,
            Experience: 270,
            Range: 50,
            EnemyControl: 6,
            ParusPriority: true
        },
        MonsterReaper: {
            Name: "MonsterReaper",
            HealPoints: 1500,
            PhysicalDamage: 100,
            LightningDamage: 0,
            MagicDamage: 100,
            AttackCooldown: 1500,
            Speed: 50,
            PhysicalProtection: 30,
            LightningProtection: 40,
            MagicProtection: 20,
            Cost: 425,
            Experience: 300,
            Range: 70,
            EnemyControl: 5,
            ParusPriority: false
        },
        MonsterBringer: {
            Name: "MonsterBringer",
            HealPoints: 2000,
            PhysicalDamage: 125,
            LightningDamage: 0,
            MagicDamage: 125,
            AttackCooldown: 1500,
            Speed: 50,
            PhysicalProtection: 30,
            LightningProtection: 40,
            MagicProtection: 20,
            Cost: 450,
            Experience: 330,
            Range: 100,
            EnemyControl: 8,
            ParusPriority: false
        },
        MonsterSprout: {
            Name: "MonsterSprout",
            HealPoints: 2000,
            PhysicalDamage: 150,
            LightningDamage: 0,
            MagicDamage: 150,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 40,
            LightningProtection: 0,
            MagicProtection: 20,
            Cost: 475,
            Experience: 360,
            Range: 70,
            EnemyControl:5,
            ParusPriority:false
        },
        MonsterNanny: {
            Name: "MonsterNanny",
            HealPoints: 2000,
            PhysicalDamage: 100,
            LightningDamage: 100,
            MagicDamage: 100,
            AttackCooldown: 1500,
            Speed: 50,
            PhysicalProtection: 40,
            LightningProtection: 0,
            MagicProtection: 0,
            Cost: 500,
            Experience: 390,
            Range: 80,
            EnemyControl:5,
            ParusPriority:false
        },
        MonsterSoulWizard: {
            Name: "MonsterSoulWizard",
            HealPoints: 2300,
            PhysicalDamage: 50,
            LightningDamage: 50,
            MagicDamage: 250,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 0,
            LightningProtection: 40,
            MagicProtection: 40,
            Cost: 525,
            Experience: 400,
            Range: 80,
            EnemyControl: 7,
            ParusPriority: false
        },
        MonsterFireWizard: {
            Name: "MonsterFireWizard",
            HealPoints: 2400,
            PhysicalDamage: 50,
            LightningDamage: 100,
            MagicDamage: 250,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 0,
            LightningProtection: 40,
            MagicProtection: 40,
            Cost: 550,
            Experience: 400,
            Range: 80,
            EnemyControl: 7,
            ParusPriority: false
        },
        MonsterGuardian: {
            Name: "MonsterGuardian",
            HealPoints: 3000,
            PhysicalDamage: 500,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 40,
            LightningProtection: 20,
            MagicProtection: 40,
            Cost: 575,
            Experience: 500,
            Range: 50,
            EnemyControl: 4,
            ParusPriority: false
        },
        MonsterMiner: {
            Name: "MonsterMiner",
            HealPoints: 2300,
            PhysicalDamage: 0,
            LightningDamage: 0,
            MagicDamage: 600,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 40,
            LightningProtection: 20,
            MagicProtection: 40,
            Cost: 600,
            Experience: 500,
            Range: 50,
            EnemyControl: 4,
            ParusPriority: false
        },
        
        BossCultist: {
            Name: "BossCultist",
            HealPoints: 8000,
            PhysicalDamage: 150,
            LightningDamage: 0,
            MagicDamage: 30,
            AttackCooldown: 2000,
            Speed: 50,
            PhysicalProtection: 30,
            LightningProtection: 0,
            MagicProtection: 30,
            Cost: 25000,
            Experience: 5000,
            Range: 80,
            EnemyControl: 7,
            ParusPriority: false
        },
        BossBlackDragon: {
            Name: "BossBlackDragon",
            HealPoints: 15000,
            PhysicalDamage: 300,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            Speed: 50,
            PhysicalProtection: 60,
            LightningProtection: 60,
            MagicProtection: 20,
            Cost: 50000,
            Experience: 7500,
            Range: 100,
            EnemyControl:7,
            ParusPriority:false
        },
        BossCthulhu: {
            Name: "BossCthulhu",
            HealPoints: 20000,
            PhysicalDamage: 300,
            LightningDamage: 0,
            MagicDamage: 300,
            AttackCooldown: 2000,
            Speed: 30,
            PhysicalProtection: 40,
            LightningProtection: 20,
            MagicProtection: 80,
            Cost: 75000,
            Experience: 10000,
            Range: 200,
            EnemyControl: 9,
            ParusPriority: false
        },
        BossDemon: {
            Name: "BossDemon",
            HealPoints: 25000,
            PhysicalDamage: 0,
            LightningDamage: 200,
            MagicDamage: 600,
            AttackCooldown: 2000,
            Speed: 100,
            PhysicalProtection: 80,
            LightningProtection: 0,
            MagicProtection: 0,
            Cost: 100000,
            Experience: 15000,
            Range: 300,
            EnemyControl: 9,
            ParusPriority: false
        },
        BossMiranda: {
            Name: "BossMiranda",
            HealPoints: 25000,
            PhysicalDamage: 200,
            LightningDamage: 600,
            MagicDamage: 200,
            AttackCooldown: 2000,
            Speed: 70,
            PhysicalProtection: 50,
            LightningProtection: 50,
            MagicProtection: 50,
            Cost: 200000,
            Experience: 20000,
            Range: 200,
            EnemyControl: 9,
            ParusPriority: false
        },
        HeroCat: {
            Name: "Кот-Рыцарь",
            HealPoints: 500,
            PhysicalDamage: 30,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            SpawnCooldown: 6000,
            SpawnBatchSize: 6,
            PhysicalProtection: 0,
            LightningProtection: 0,
            MagicProtection: 0,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 25,
            Range: 30,
            EnemyControl: 3
        },
        HeroReaper: {
            Name: "Жнец",
            HealPoints: 750,
            PhysicalDamage: 50,
            LightningDamage: 0,
            MagicDamage: 10,
            AttackCooldown: 1000,
            SpawnCooldown: 6000,
            SpawnBatchSize: 4,
            PhysicalProtection: 10,
            LightningProtection: 40,
            MagicProtection: 10,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 80,
            MPCost: 30,
            Range: 60,
            EnemyControl: 4
           
        },
        HeroArchaeologist: {
            Name: "Археолог",
            HealPoints: 750,
            PhysicalDamage: 100,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            SpawnCooldown: 6000,
            SpawnBatchSize: 4,
            PhysicalProtection: 15,
            LightningProtection: 0,
            MagicProtection: 0,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 80,
            MPCost: 30,
            Range: 60,
            EnemyControl: 3,
            InFight: false
        },
        HeroCenturion: {
            Name: "Центурион Рори",
            HealPoints: 900,
            PhysicalDamage: 150,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 1000,
            SpawnCooldown: 8000,
            SpawnBatchSize: 6,
            PhysicalProtection: 30,
            LightningProtection: 0,
            MagicProtection: 0,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 35,
            Range: 60,
            EnemyControl: 5,
        },
        HeroMage: {
            Name: "Тёмный Маг",
            HealPoints: 1200,
            PhysicalDamage: 30,
            LightningDamage: 0,
            MagicDamage: 70,
            AttackCooldown: 1000,
            SpawnCooldown: 6000,
            SpawnBatchSize: 3,
            PhysicalProtection: 0,
            LightningProtection: 0,
            MagicProtection: 40,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 35,
            Range: 60,
            EnemyControl: 4,
        },
        HeroTesla: {
            Name: "Тесла",
            HealPoints: 1500,
            PhysicalDamage: 0,
            LightningDamage: 100,
            MagicDamage: 0,
            AttackCooldown: 1000,
            SpawnCooldown: 10000,
            SpawnBatchSize: 4,
            PhysicalProtection: 20,
            LightningProtection: 30,
            MagicProtection: 20,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 35,
            Range: 30,
            EnemyControl: 4,
        },
        HeroSceleton: {
            Name: "Big Bone",
            HealPoints: 2500,
            PhysicalDamage: 300,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 3000,
            SpawnCooldown: 8000,
            SpawnBatchSize: 4,
            PhysicalProtection: 0,
            LightningProtection: 20,
            MagicProtection: 0,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 40,
            Range: 80,
            EnemyControl: 5,
        },
        HeroWitch: {
            Name: "Ведьмочка",
            HealPoints: 2000,
            PhysicalDamage: 0,
            LightningDamage: 0,
            MagicDamage: 300,
            AttackCooldown: 2000,
            SpawnCooldown: 10000,
            SpawnBatchSize: 5,
            PhysicalProtection: 0,
            LightningProtection: 0,
            MagicProtection: 50,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 80,
            MPCost: 40,
            Range: 60,
            EnemyControl: 4

        },
        HeroNightmare: {
            Name: "Кошмар",
            HealPoints: 4000,
            PhysicalDamage: 300,
            LightningDamage: 0,
            MagicDamage: 300,
            AttackCooldown: 2000,
            SpawnCooldown: 20000,
            SpawnBatchSize: 1,
            PhysicalProtection: 20,
            LightningProtection: 0,
            MagicProtection: 30,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 150,
            MPCost: 50,
            Range: 50,
            EnemyControl: 6
        
        },
        HeroMinotaur: {
            Name: "Минотавр",
            HealPoints: 5000,
            PhysicalDamage: 500,
            LightningDamage: 0,
            MagicDamage: 0,
            AttackCooldown: 3000,
            SpawnCooldown: 30000,
            SpawnBatchSize: 1,
            PhysicalProtection: 50,
            LightningProtection: 0,
            MagicProtection: 0,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 50,
            Range: 30,
            EnemyControl: 10,
            InFight: false
        },
        HeroStormhead: {
            Name: "Ш.Т.О.Р.М",
            HealPoints: 1500,
            PhysicalDamage: 0,
            LightningDamage: 250,
            MagicDamage: 0,
            AttackCooldown: 3000,
            SpawnCooldown: 20000,
            SpawnBatchSize: 3,
            PhysicalProtection: 20,
            LightningProtection: 30,
            MagicProtection: 20,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 50,
            MPCost: 50,
            Range: 100,
            EnemyControl: 10,
        },
        HeroWizard: {
            Name: "Чародей",
            HealPoints: 2000,
            PhysicalDamage: 0,
            LightningDamage: 0,
            MagicDamage: 350,
            AttackCooldown: 1500,
            SpawnCooldown: 20000,
            SpawnBatchSize: 3,
            PhysicalProtection: 20,
            LightningProtection: 30,
            MagicProtection: 20,
            CriticalChance: 1,
            CriticalDamage: 300,
            Speed: 100,
            MPCost: 50,
            Range: 60,
            EnemyControl: 5,
        },
        BuildingPodkova: {
            Name: "Подкова",
            Description: "Увеличение кол-ва \nвыпадающих монет \n(+1%/LVL)",
            MPCost: 0,
            CoolDown: 0
        },
        BuildingMPObelisk: {
            Name: "Обелиск Магии",
            Description: "Мгновенно \nвосстанавливает 50% MP",
            MPCost: 0,
            CoolDown: 80000
        },
        BuildingHPObelisk: {
            Name: "Обелиск Жизни",
            Description: "Мгновенно \nвосстанавливает 50% HP",
            MPCost: 0.3,
            CoolDown: 80000
        },
        BuildingCDObelisk: {
            Name: "Обелиск Времени",
            Description: "Мгновенно \nобнуляет перезарядку \nгероев",
            MPCost: 0.1,
            CoolDown: 30000
        },
        BuildingPlasmaGun: {
            Name: "BFG-9000",
            Description: "Уничтожает всех \nпротивников на поле",
            MPCost: 0.3,
            CoolDown: 60000
        }
    },
    HERO_SLOTS: {
        0: {
            x: 450,
            y: 746
        },
        1: {
            x: 710,
            y: 746
        },
        2: {
            x: 450,
            y: 625
        },
        3: {
            x: 710,
            y: 625
        },
        4: {
            x: 450,
            y: 506
        },
        5: {
            x: 710,
            y: 506
        },
    },
    DEPTHS: {
        ToolBarClose: 5000,
        ToolBarField: 5002,
        ToolBarPrimal: 5003,
        ToolBarMinor: 5001,
        ToolBarRecyclerView: 5004,
        HeroesBarField: 5006,
        HeroesBarClose: 5005,
        HeroesBarRecyclerView: 5007,
        Slots: 1000,
        Effects: 8000,
        Dialogue: 10000,
        DialogueButton: 10001
    },
    WAVE_GENERATOR: {
        MinSpawnDelay: 500,
        SpawnDelayVariety: 200,
        PlateauSpawnWave: 1000,
        MinMonsterAmount: 5,
        MonsterWaveCoefficient: 3,
        MaximumMomentMonsters: 30,
        WavesPerBoss: 10,
        MonsterPreferences: {
            MonsterSlime: {
                MinWave: 1,
                MaxWave: 20,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterTwig: {
                MinWave: 1,
                MaxWave: 30,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterBrainer: {
                MinWave: 10,
                MaxWave: 50,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterHellhound: {
                MinWave: 20,
                MaxWave: 60,
                MinBatch: 3,
                MaxBatch: 4,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterGhoul: {
                MinWave: 30,
                MaxWave: 80,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterBot: {
                MinWave: 70,
                MaxWave: 130,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterDarkKnight: {
                MinWave: 60,
                MaxWave: 120,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterHedgehog: {
                MinWave: 40,
                MaxWave: 160,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterSlayer: {
                MinWave: 100,
                MaxWave: 190,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterToaster: {
                MinWave: 90,
                MaxWave: 150,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterWorm: {
                MinWave: 160,
                MaxWave: 260,
                MinBatch: 3,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterIEM: {
                MinWave: 120,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterSprout: {
                MinWave: 230,
                MaxWave: 350,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterBringer: {
                MinWave: 210,
                MaxWave: 300,
                MinBatch: 2,
                MaxBatch: 5,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterReaper: {
                MinWave: 180,
                MaxWave: 290,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterSoulWizard: {
                MinWave: 270,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterFireWizard: {
                MinWave: 290,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterNecromancer: {
                MinWave: 140,
                MaxWave: 250,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterGuardian: {
                MinWave: 310,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterMiner: {
                MinWave: 330,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            MonsterNanny: {
                MinWave: 250,
                MaxWave: 420,
                MinBatch: 1,
                MaxBatch: 3,
                HealthBoost: 0.01,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            BossCultist: {
                MinWave: 10,
                MaxWave: 100,
                MinBatch: 1,
                MaxBatch: 1,
                HealthBoost: 0.02,
                AttackBoost: 0.02,
                BatchComparativeBoost: 0.1
            },
            BossBlackDragon: {
                MinWave: 20,
                MaxWave: 300,
                MinBatch: 1,
                MaxBatch: 1,
                HealthBoost: 0.02,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            BossDemon: {
                MinWave: 100,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 1,
                HealthBoost: 0.02,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            BossMiranda: {
                MinWave: 200,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 1,
                HealthBoost: 0.02,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            },
            BossCthulhu: {
                MinWave: 50,
                MaxWave: -1,
                MinBatch: 1,
                MaxBatch: 1,
                HealthBoost: 0.02,
                AttackBoost: 0.01,
                BatchComparativeBoost: 0.1
            }
        }
    }
}